import assert from 'node:assert/strict'
import test from 'node:test'
import { createLearningSpaceService, LearningSpaceConflictError } from '../../../src/lib/learning-space-service'
import { AuthorizationError } from '../../../src/lib/server-authorization'

const now = new Date('2026-09-16T00:00:00.000Z')
function repo() {
  const spaces = new Map<string, any>(); const members = new Map<string, any>(); const topics = new Map<string, any>(); const activities: any[] = []; const bookings = new Map<string, any>([['legacy', { id: 'legacy', mentorId: 'a', menteeId: 'b', status: 'COMPLETED', learningSpaceId: null }], ['confirmed', { id: 'confirmed', mentorId: 'a', menteeId: 'b', status: 'CONFIRMED', learningSpaceId: null }]]); let next = 1
  const key = (s: string, u: string) => `${s}:${u}`
  const tx: any = { lock: async () => {}, space: async (id: string) => spaces.get(id) ?? null, member: async (s: string, u: string) => members.get(key(s,u)) ?? null, activeMemberCount: async (s: string) => [...members.values()].filter(m => m.learningSpaceId === s && m.status === 'ACTIVE').length, userExists: async (id: string) => ['a','b','c','d'].includes(id), skillExists: async (id: string) => ['skill-1','skill-2'].includes(id), createSpace: async (data: any) => { const x={ id:`s${next++}`,state:'ACTIVE',version:1,updatedById:null,archivedAt:null,createdAt:now,updatedAt:now,...data }; spaces.set(x.id,x); return x }, createMember: async (s:string,u:string) => { const x={learningSpaceId:s,userId:u,status:'ACTIVE',joinedAt:now,leftAt:null}; members.set(key(s,u),x); return x }, reactivateMember: async (s:string,u:string) => { const x=members.get(key(s,u)); x.status='ACTIVE'; return x }, booking: async (id:string) => bookings.get(id) ?? null, attachBooking: async (id:string,s:string) => { const b=bookings.get(id); if (b.learningSpaceId) throw new LearningSpaceConflictError('Booking is already associated with a learning space'); b.learningSpaceId=s }, updateSpace: async (id:string,v:number,data:any) => { const x=spaces.get(id); if (!x || x.version!==v) return null; Object.assign(x,data,{version:v+1}); return x }, topic: async (s:string,id:string) => { const x=topics.get(id); return x?.learningSpaceId===s ? x : null }, topics: async (s:string) => [...topics.values()].filter(t=>t.learningSpaceId===s), createTopic: async (data:any) => { const x={id:`t${next++}`,state:'ACTIVE',archivedAt:null,createdAt:now,updatedAt:now,...data}; topics.set(x.id,x); return x }, updateTopic: async (id:string,data:any) => Object.assign(topics.get(id),data), activity: async (x:any) => { activities.push(x) }, reusable: async ({memberIds,primarySkillId}:any) => [...spaces.values()].filter(s=>s.state==='ACTIVE'&&s.primarySkillId===primarySkillId&&memberIds.every((u:string)=>members.get(key(s.id,u))?.status==='ACTIVE')) }
  return { findSpaceMembership: async ({spaceId,userId}:any) => ({spaceExists:spaces.has(spaceId),membership:members.get(key(spaceId,userId))??null}), transaction: async (f:any) => f(tx), spaces,members,topics,activities,bookings }
}
function service(actor='a') { const r=repo(); const s=createLearningSpaceService({ repository:r as any, requireAuthenticatedUser:async()=>({id:actor,email:null,name:null}), requireLearningSpaceMember:async id=>{const m=await r.findSpaceMembership({spaceId:id,userId:actor}); if(!m.spaceExists)throw new AuthorizationError(404,'Learning space not found'); if(!m.membership)throw new AuthorizationError(403,'Learning space membership required'); return {user:{id:actor,email:null,name:null},membership:m.membership}}, now:()=>now }); return {r,s} }
test('B2 allows exactly two active members, permits repeated pair spaces, and suggests without forcing reuse', async () => { const {r,s}=service(); const one=await s.createDirect({memberId:'b',title:'One',primarySkillId:'skill-1'}); const two=await s.createDirect({memberId:'b',title:'Two',primarySkillId:'skill-1'}); assert.notEqual(one.id,two.id); assert.equal((await s.suggestReuse({memberId:'b',primarySkillId:'skill-1'})).length,2); await assert.rejects(s.addMember(one.id,{memberId:'c'}),(e:any)=>e instanceof LearningSpaceConflictError); assert.equal(await r.bookings.get('legacy').learningSpaceId,null) })
test('B2 rejects nonmembers and optimistic conflicts, while retaining archived topic references and primary-skill audit', async () => { const {r,s}=service(); const space=await s.createDirect({memberId:'b',title:'One',primarySkillId:'skill-1'}); const topic=await s.addTopic(space.id,{label:'History'}); const booking={topicId:topic.id}; await s.archiveTopic(space.id,topic.id); assert.equal(booking.topicId,topic.id); const changed=await s.changePrimarySkill(space.id,{expectedVersion:1,primarySkillId:'skill-2'}); assert.equal(r.activities.at(-1).eventType,'LEARNING_SPACE_PRIMARY_SKILL_CHANGED'); await assert.rejects(s.updateDetails(space.id,{expectedVersion:1,objective:'lost'}),(e:any)=>e instanceof LearningSpaceConflictError); const other=service('c'); other.r.spaces.set(space.id,changed); other.r.members.set(`${space.id}:a`,{learningSpaceId:space.id,userId:'a',status:'ACTIVE'}); await assert.rejects(other.s.read(space.id),(e:any)=>e instanceof AuthorizationError&&e.status===403); await assert.rejects(other.s.addTopic(space.id,{label:'no'}),(e:any)=>e instanceof AuthorizationError&&e.status===403) })