'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useSession } from 'next-auth/react'
import { useEffect, useState } from 'react'
import { ArrowRight, LockKeyhole, Users } from 'lucide-react'

type Preview = { invite: { primarySkillName: string | null; objective: string | null } | null; status: string; canAccept: boolean }

const privateStateMessage: Record<string, string> = { EXPIRED: 'Liên kết này đã hết hạn.', REVOKED: 'Liên kết này không còn hiệu lực.', ACCEPTED: 'Liên kết này đã được sử dụng.', default: 'Liên kết mời không thể sử dụng.' }
const safeAcceptMessage = (message: unknown) => {
  if (typeof message === 'string' && /own Learning invite/.test(message)) return 'Bạn không thể tham gia liên kết do chính mình tạo.'
  if (typeof message === 'string' && /expired/.test(message)) return privateStateMessage.EXPIRED
  if (typeof message === 'string' && /revoked|already used|different user|usage limit|third active member/.test(message)) return privateStateMessage.ACCEPTED
  return 'Không thể tham gia LearningSpace. Vui lòng thử lại.'
}

export function LearningInviteJoin({ token }: { token: string }) {
  const router = useRouter(); const { status: sessionStatus } = useSession()
  const [preview, setPreview] = useState<Preview | null>(null); const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  useEffect(() => { let live = true; fetch('/api/learning/invites/preview', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token }) }).then(async response => ({ response, data: await response.json() })).then(({ response, data }) => { if (!live) return; if (!response.ok) { setError('Liên kết mời không thể sử dụng.'); return } setPreview(data.preview) }).catch(() => live && setError('Không thể kiểm tra liên kết mời. Vui lòng thử lại.')); return () => { live = false } }, [token])
  const callbackUrl = `/learning/invite/${encodeURIComponent(token)}`
  async function accept() { setPending(true); setError(''); try { const response = await fetch('/api/learning/invites/accept', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({}) }); const data = await response.json(); if (!response.ok) { setError(safeAcceptMessage(data.error)); return } router.replace(`/learning/${data.space.id}?onboarding=invite`) } catch { setError('Không thể tham gia LearningSpace. Vui lòng thử lại.') } finally { setPending(false) } }
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-xl"><Link href="/" className="text-sm font-medium text-purple-700 underline-offset-4 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-600">← Về GiveGot</Link><section className="mt-5 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-8" aria-labelledby="invite-heading"><Users aria-hidden="true" className="h-7 w-7 text-purple-600" /><h1 id="invite-heading" className="mt-3 text-2xl font-bold text-slate-950">Học cùng người bạn đã có</h1>{!preview && !error && <p role="status" className="mt-4 text-sm text-slate-600">Đang kiểm tra liên kết mời…</p>}{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{preview && !preview.canAccept && <div className="mt-4" role="status"><p className="text-sm text-slate-700">{privateStateMessage[preview.status] || privateStateMessage.default}</p>{sessionStatus === 'authenticated' && preview.status === 'ACCEPTED' && <button type="button" onClick={accept} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-purple-600 px-4 py-2.5 text-sm font-semibold text-white">Mở LearningSpace <ArrowRight aria-hidden="true" className="h-4 w-4" /></button>}</div>}{preview?.canAccept && <><p className="mt-3 text-sm leading-6 text-slate-600">Bạn được mời tạo một LearningSpace riêng tư cho hai người.</p><dl className="mt-5 space-y-4 rounded-xl bg-slate-50 p-4"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Kỹ năng chính</dt><dd className="mt-1 font-semibold text-slate-950">{preview.invite?.primarySkillName || 'Kỹ năng học tập'}</dd></div>{preview.invite?.objective && <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">Mục tiêu chung</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{preview.invite.objective}</dd></div>}</dl>{sessionStatus === 'unauthenticated' ? <Link href={`/auth/signin?callbackUrl=${encodeURIComponent(callbackUrl)}`} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-purple-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-purple-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-600 focus-visible:ring-offset-2"><LockKeyhole aria-hidden="true" className="h-4 w-4" />Đăng nhập hoặc tạo tài khoản</Link> : <button type="button" onClick={accept} disabled={pending || sessionStatus !== 'authenticated'} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-purple-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-purple-700 disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-600 focus-visible:ring-offset-2">{pending ? 'Đang tham gia…' : 'Tham gia LearningSpace'} <ArrowRight aria-hidden="true" className="h-4 w-4" /></button>}</>}</section></div></main>
}
